[package]
name = "sgx_serialize"
version = "1.0.5"
authors = ["Baidu"]

[lib]
name = "sgx_serialize"
path = "../../../rust-sgx-sdk/sgx_serialize/src/lib.rs"
crate-type = ["rlib"]

[features]
default = []

[dependencies]