[package]
name = "sgx_tunittest"
version = "1.0.5"
authors = ["Baidu"]

[lib]
name = "sgx_tunittest"
path = "../../../rust-sgx-sdk/sgx_tunittest/src/lib.rs"
crate-type = ["rlib"]

[features]
default = []

[dependencies]